// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// shuffle_topm
List shuffle_topm(NumericMatrix y, IntegerVector group, Nullable<NumericMatrix> weights, IntegerMatrix combM, IntegerVector geneSubset, int seed);
RcppExport SEXP _OVESEG_shuffle_topm(SEXP ySEXP, SEXP groupSEXP, SEXP weightsSEXP, SEXP combMSEXP, SEXP geneSubsetSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type combM(combMSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type geneSubset(geneSubsetSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_topm(y, group, weights, combM, geneSubset, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OVESEG_shuffle_topm", (DL_FUNC) &_OVESEG_shuffle_topm, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_OVESEG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
