# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' pairwise t-statistics (unscaled)
#'
#' @param ymean a numeric matrix containing group means.
#' @param stdevUnscaled a numeric matrix containing unscaled standard
#'     deviations of the group means.
pairwise_tstat_unscaled <- function(ymean, stdevUnscaled) {
    .Call('_OVESEG_pairwise_tstat_unscaled', PACKAGE = 'OVESEG', ymean, stdevUnscaled)
}

#' p-value by weighted estimation
#'
#' @param tt a vector of test statistics.
#' @param ttperm a matrix of test statistics from permutaitons.
#' @param W a matrix containing weights for each spot in ttperm.
#' @export
pvalue_weighted_est <- function(tt, ttperm, w) {
    .Call('_OVESEG_pvalue_weighted_est', PACKAGE = 'OVESEG', tt, ttperm, w)
}

#' min value for each row
#'
#' @param Y a numeric matrix.
row_min <- function(Y) {
    .Call('_OVESEG_row_min', PACKAGE = 'OVESEG', Y)
}

#' which.max for each row
#'
#' @param Y a numeric matrix
row_which_max <- function(Y) {
    .Call('_OVESEG_row_which_max', PACKAGE = 'OVESEG', Y)
}

#' Shuffle the top M groups
#'
#' @param y a numeric matrix to be shuffled.
#' @param group a integer vector indicating group indexes.
#' @param weights optional numeric matrix containing prior weights.
#' @param combM a integer matrix with each row giving one choice of M groups
#' @param geneSubset a integer vector indicating the probe pattern of combM
#' @param seed an integer seed for the random number generator.
shuffle_topm <- function(y, group, weights, combM, geneSubset, seed) {
    .Call('_OVESEG_shuffle_topm', PACKAGE = 'OVESEG', y, group, weights, combM, geneSubset, seed)
}

